# Generated by Django 3.0 on 2020-12-26 20:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('dni', models.IntegerField(default=0, verbose_name='DNI')),
                ('names', models.CharField(max_length=100, verbose_name='Nombre/s')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellido/s')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Elector',
                'verbose_name_plural': 'Electores',
                'ordering': ['surnames', 'names'],
            },
        ),
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField(unique=True)),
                ('electores', models.ManyToManyField(to='core.Elector')),
            ],
            options={
                'verbose_name': 'Padron',
                'verbose_name_plural': 'Padrones',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('candidate_number', models.IntegerField(default=1)),
                ('slug', models.SlugField(unique=True)),
                ('eleccion_estatus', models.IntegerField(choices=[(1, 'Aún no ha iniciado.'), (2, 'En curso'), (3, 'Finalizada'), (4, 'Suspendida'), (5, 'Potergada')], default=1)),
                ('eleccion_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cargo')),
                ('eleccion_padron', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Padron')),
            ],
            options={
                'verbose_name': 'Eleccion',
                'verbose_name_plural': 'Elecciones',
                'ordering': ['date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('postulation_date', models.DateField(auto_now_add=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('candidato_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cargo')),
                ('candidato_eleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Eleccion')),
                ('candidato_elector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Elector')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['candidato_cargo', 'postulation_date'],
            },
        ),
        migrations.CreateModel(
            name='Sufragio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('has_voted', models.BooleanField(default=False)),
                ('hash', models.UUIDField(default=uuid.uuid4)),
                ('voting_time', models.DateTimeField(auto_now_add=True)),
                ('sufragio_eleccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Eleccion')),
                ('sufragio_elector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Elector')),
            ],
            options={
                'verbose_name': 'Sufragio',
                'verbose_name_plural': 'Sufragios',
                'ordering': ['sufragio_eleccion', 'sufragio_elector'],
                'unique_together': {('sufragio_eleccion', 'sufragio_elector')},
            },
        ),
    ]
