# Generated by Django 3.0 on 2020-12-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleccion',
            name='candidate_number',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cargo'),
        ),
    ]
