# Generated by Django 3.0 on 2021-01-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201229_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleccion',
            name='eleccion_estatus',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Programada'), (2, 'En curso'), (3, 'Finalizada'), (4, 'Suspendida'), (5, 'Potergada')], default=0),
        ),
    ]
