# Generated by Django 3.0 on 2021-02-06 11:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('dni', models.IntegerField(default=0, verbose_name='DNI')),
                ('names', models.CharField(max_length=100, verbose_name='Nombre/s')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellido/s')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Elector',
                'verbose_name_plural': 'Electores',
                'ordering': ['surnames', 'names'],
            },
        ),
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField(unique=True)),
                ('electores', models.ManyToManyField(to='padron.Elector')),
            ],
            options={
                'verbose_name': 'Padron',
                'verbose_name_plural': 'Padrones',
                'ordering': ['date', 'id'],
            },
        ),
    ]
