# Generated by Django 3.0 on 2021-02-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='eleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleccion.Eleccion'),
        ),
    ]
